version: '3.3'
services:
  python:
    build: .
    volumes:
    - .:/var/www
    working_dir: /var/www
    restart: always
    networks:
      default:
        aliases:
          - image_generator_python
    ports:
    - "8021:8000"
