version: '3.3'
services:
  nginx:
    image: nginx:1.16.0
    volumes:
    - .:/usr/share/nginx/html
    working_dir: /usr/share/nginx/html
    restart: always
    networks:
      default:
        aliases:
          - image_generator
    ports:
    - "8021:80"
