#!/usr/bin/env python

from common import get_args

import cgi
import os
import json

def create_template(svg):
   return svg

def main():
   form = cgi.FieldStorage()

   # Get filename here.
   fileitem = form['filename']

   # Test if the file was uploaded
   if not fileitem.filename:
      print('No filename')
      return

   # strip leading path from file name to avoid
   # directory traversal attacks
   filename = os.path.basename(fileitem.filename)
   if not filename.endswith('.svg'):
      print('Upload only svg files')
      return

   files = [ f for f in os.listdir('.') if f.endswith('.svg') ]
   if filename in files:
      print('File with this name already exists')
      return

   with open('data/templates.json', 'r') as f:
      templates = json.load(f)

   if filename in templates:
      print('Template with the same name already exists')
      return

   with open('data/' + filename, 'wb') as out:
      svg = fileitem.file.read()
      svg = create_template(svg)
      out.write(svg)

   templates[filename[:-4]] = form['title'].value

   data = json.dumps(templates, ensure_ascii=False)
   with open('data/templates.json', 'w') as f:
      f.write(data)

   print('Success')

print('Content-Type: text/html')
print()

main()
