#!/usr/bin/env python

import json
import cgi
import requests
import base64

def cgi_args():
    args = {}
    storage = cgi.FieldStorage()
    for key in storage.keys():
        args[key] = storage[key].value
    return args

print("Content-type: text/html")
print()
print('''
<!DOCTYPE html>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<style>
#canvas {
    display: none;
}
</style>
''')

args = cgi_args()

img_url = args['url'];
response = requests.get(img_url, stream=True)
img_type = response.headers['Content-Type']
base64 = base64.b64encode(response.content)
uri = "data:{};base64,{}".format(img_type, base64)

template = args['template'] + '.svg';
with open(template, 'r') as f:
    text = args['text'];
    svg = f.read().replace('%TEXT%', text).replace('%IMAGE%', uri)
    print(svg)
    with open('test.svg', 'w') as out:
        out.write(svg)
        exec('convert test.svg test.png');

print('''
<br>
<canvas id="canvas" width="1200" height="600"></canvas>
<br>

<button>Download</button>

<script>
	var btn = document.querySelector('button');
	var svg = document.querySelector('svg');
	var canvas = document.querySelector('canvas');

	function triggerDownload (imgURI) {
		var evt = new MouseEvent('click', {
			view: window,
			bubbles: false,
			cancelable: true
		});

		var a = document.createElement('a');
		a.setAttribute('download', 'MY_COOL_IMAGE.png');
		a.setAttribute('href', imgURI);
		a.setAttribute('target', '_blank');

		a.dispatchEvent(evt);
	}

	btn.addEventListener('click', function () {
		var canvas = document.getElementById('canvas');
		var ctx = canvas.getContext('2d');
		var data = (new XMLSerializer()).serializeToString(svg);
		var DOMURL = window.URL || window.webkitURL || window;

		var img = new Image();
		img.crossOrigin = "Anonymous";

		if (navigator.userAgent.indexOf('Chrome') != -1) {
			var url = 'data:image/svg+xml;base64,' + btoa(unescape(encodeURIComponent(data)));
		} else {
			var svgBlob = new Blob([data], {type: 'image/svg+xml;charset=utf-8'});
			var url = DOMURL.createObjectURL(svgBlob);
		}

		img.onload = function () {
			ctx.drawImage(img, 0, 0);
			DOMURL.revokeObjectURL(url);

			var imgURI = canvas
				.toDataURL('image/png')
				.replace('image/png',
				'image/octet-stream');

			triggerDownload(imgURI);
		};

		img.src = url;
	});
''')

if args["download"] == "on":
    print("btn.click();")

print('''
</script>
''')
